name: MacRDP

on:
  workflow_dispatch:

jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Enabling Remote Access
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
          chmod +x mac/start.sh
          bash mac/start.sh "$NGROK_AUTH_TOKEN"
          
    - name: Log In Details To VNC Server
      run: |
         chmod +x mac/login.sh
         bash mac/login.sh
         
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v3
